config/routes.rb
Rails.application.routes.draw do
  root to: "import#new"

  resource :import, only: %w(new show create), controller: "import"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :password, 
    presence: true, 
    length: { within: 10..16 }

  validate :password_complexity, if: -> { password.present? }

  PASSWORD_COMPLEXITY_RULES = {
    "must contain at least one lowercase character" => /[a-z]+/,
    "must contain at least one uppercase character" => /[A-Z]+/,
    "must contain at least one digit" => /\d+/,
    "must not contain three consecutive repeating characters" => /^(?:([a-zA-Z0-9])(?!\1\1+))*$/ }

  def self.import_csv(file)
    CsvImporter.new(file).call
  end

  def changes_until_valid_password
    validate
    password_errors = errors.where(:password)
    return 0 if password_errors.blank? 

    count = 0 
    password_errors.each do |error|
      if error.type == :too_short
        count += error.options[:count] - password.size 
        break
      elsif error.type == :too_long
        count += password.size - error.options[:count]
        break
      elsif error.type =~ /lowercase/
        count += 1
      elsif error.type =~ /uppercase/
        count += 1
      elsif error.type =~ /three consecutive repeating/
        password_dup = password.dup
        while (match = password_dup.match('(.)\1\1+'))
          matched = match[0]
          password_dup.gsub!(matched, matched[0..1] + matched[2].next + matched[3..-1])
          count += 1
        end
      end
    end
    count
  end

  private

  def password_complexity
    PASSWORD_COMPLEXITY_RULES.each do |message, pattern|
      errors.add(:password, message) unless password.match(pattern)
    end
  end
end

app/models/user/csv_importer.rb
require 'csv'

class User::CsvImporter
  def initialize(file)
    @file = file
  end

  def call
    result = []
    CSV.foreach(@file.path, headers: true) do |row|
      user = User.new(row.to_hash)
      if user.save
        result << "#{user.name} was successfully saved"
      else
        non_password_related_errors = user.errors.reject { |error| error.attribute == :password }
        if non_password_related_errors.present?
          result << non_password_related_errors.map(&:full_message)
        elsif (required_changes = user.changes_until_valid_password)
          result << "Change #{required_changes} #{'character'.pluralize(required_changes)} of #{user.name} password"
        end
      end
    end
    result
  rescue CSV::MalformedCSVError
    raise "Invalid csv file"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  def new
  end

  def show
  end

  def create
    result = User.import_csv(import_params[:file])
    flash[:import_notice] = result
    redirect_to import_path
  end

  private

  def import_params
    params.permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/views/import/create.html.erb
<h1>Import#create</h1>

app/views/import/new.html.erb
<h1>CSV Import</h1>
<%= form_tag import_path, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <br/>
  <%= submit_tag "Import" %>
<% end %>

app/views/import/show.html.erb
<h1>Result</h1>
<% if flash[:import_notice] %>
  <% flash[:import_notice].each do |msg| %>
    <% if msg.is_a?(Array) %>
      <p><%= msg.join(", ") %></p>
    <% else %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
<% end %>
<%= link_to "New Import", new_import_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserImport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>